sfdx-source/main/objects/External_Nlp_Model_Setting__mdt/External_Nlp_Model_Setting__mdt.object-meta.xml
<CustomObject>
    <label>External Nlp Model Setting</label>
    <pluralLabel>External Nlp Model Settings</pluralLabel>
</CustomObject>

sfdx-source/main/objects/External_Nlp_Model_Setting__mdt/fields/External_Nlp_Service_Setting__c.field-meta.xml
<CustomField>
    <fullName>External_Nlp_Service_Setting__c</fullName>
    <label>External Nlp Service Setting</label>
    <referenceTo>External_Nlp_Service_Setting__mdt</referenceTo>
    <relationshipLabel>External Nlp Model Settings</relationshipLabel>
    <relationshipName>External_Nlp_Model_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/main/objects/External_Nlp_Model_Setting__mdt/fields/Model_Id__c.field-meta.xml
<CustomField>
    <fullName>Model_Id__c</fullName>
    <label>Model Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/objects/External_Nlp_Model_Setting__mdt/fields/Named_Credential_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential_Name__c</fullName>
    <label>Named Credential Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/main/objects/External_Nlp_Service_Setting__mdt/External_Nlp_Service_Setting__mdt.object-meta.xml
<CustomObject>
    <label>External Nlp Service Setting</label>
    <pluralLabel>External Nlp Service Settings</pluralLabel>
</CustomObject>

sfdx-source/main/objects/External_Nlp_Service_Setting__mdt/fields/Additional_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Additional_Parameters__c</fullName>
    <inlineHelpText>Comma separated values for additional settings (e.g. sessionId=12345,verbose=true,...)</inlineHelpText>
    <label>Additional Parameters</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/main/objects/External_Nlp_Service_Setting__mdt/fields/Intent_Confidence_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Intent_Confidence_Threshold__c</fullName>
    <label>Intent Confidence Threshold</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/objects/External_Nlp_Service_Setting__mdt/fields/NER_Confidence_Threshold__c.field-meta.xml
<CustomField>
    <fullName>NER_Confidence_Threshold__c</fullName>
    <label>NER Confidence Threshold</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/objects/External_Nlp_Service_Setting__mdt/fields/Sentiment_Confidence_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Sentiment_Confidence_Threshold__c</fullName>
    <label>Sentiment Confidence Threshold</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

sfdx-source/main/objects/External_Nlp_Service_Setting__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EINSTEIN_AI</fullName>
                <default>true</default>
                <label>EINSTEIN_AI</label>
            </value>
            <value>
                <fullName>DIALOG_FLOW</fullName>
            </value>
            <value>
                <fullName>WIT_AI</fullName>
            </value>
            <value>
                <fullName>WATSON</fullName>
            </value>
            <value>
                <fullName>LUIS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/main/classes/ExternalNlpServiceFactory.cls
public with sharing class ExternalNlpServiceFactory {

    public static ExternalNlpService makeNlpServiceFromCustomMetadata(String customMetadataName){
        External_Nlp_Service_Setting__mdt setting = getCustomMetadata(customMetadataName);

        Map<String, ExternalNlpServiceType> extNlpServiceTypeMap = new Map<String, ExternalNlpServiceType>();
        for(ExternalNlpServiceType v : ExternalNlpServiceType.values()) {
            extNlpServiceTypeMap.put(v.name(), v);
        }

        ExternalNlpServiceType serviceType = extNlpServiceTypeMap.get(setting.Type__c);
        Map<String,String> additionalParametersMap = ExternalNlpUtils.convertStringToMap(setting.Additional_Parameters__c);
        Decimal intentConfidenceThreshold = setting.Intent_Confidence_Threshold__c;
        Decimal nerConfidenceThreshold = setting.NER_Confidence_Threshold__c;
        Decimal sentimentConfidenceThreshold = setting.Sentiment_Confidence_Threshold__c;

        List<ExternalNlpModelParameters> modelParams = new List<ExternalNlpModelParameters>();

        if (Test.isRunningTest()) {
            modelParams.add(new ExternalNlpModelParameters.Builder()
                .setModelId('TestModelId')
                .setNamedCredentialKey('TestNamedCredentialKey')
                .build());
        } else {
            for (External_Nlp_Model_Setting__mdt modelSetting : setting.External_Nlp_Model_Settings__r) {
                modelParams.add(new ExternalNlpModelParameters.Builder()
                    .setModelId(modelSetting.Model_Id__c)
                    .setNamedCredentialKey(modelSetting.Named_Credential_Name__c)
                    .build());
            }
        }

        ExternalNlpServiceParameters serviceParams = new ExternalNlpServiceParameters.Builder()
            .setModelParams(modelParams)
            .setIntentThreshold(intentConfidenceThreshold == null ? null : intentConfidenceThreshold.doubleValue())
            .setNerThreshold(nerConfidenceThreshold == null ? null : nerConfidenceThreshold.doubleValue())
            .setSentimentThreshold(sentimentConfidenceThreshold == null ? null : sentimentConfidenceThreshold.doubleValue())
            .setAdditionalParams(additionalParametersMap)
            .build();

        return makeNlpService(serviceType, serviceParams);
    }

    public static ExternalNlpService makeNlpService(ExternalNlpServiceType serviceType, ExternalNlpServiceParameters serviceParams){
        switch on serviceType {
            when EINSTEIN_AI {
                return new EinsteinAiService(serviceParams);
            } when DIALOG_FLOW {
                return new DialogFlowService(serviceParams);
            } when WIT_AI {
                return new WitAiService(serviceParams);
            } when LUIS {
                return new LuisService(serviceParams);
            } when WATSON {
                return new WatsonService(serviceParams);
            } when else {
                throw new ExternalNlpServiceException('Service type has no implementation', ExternalNlpServiceExceptionCode.UNSUPPORTED_SERVICE_TYPE);
            }
        }
    }

    private static External_Nlp_Service_Setting__mdt getCustomMetadata(String customMetadataName) {
        List<External_Nlp_Service_Setting__mdt> settings = new List<External_Nlp_Service_Setting__mdt>();
        if (Test.isRunningTest()) {
            External_Nlp_Service_Setting__mdt testSetting = new External_Nlp_Service_Setting__mdt(
                DeveloperName = 'Test',
                Type__c = 'EINSTEIN_AI',
                Additional_Parameters__c = 'param1=value1',
                Intent_Confidence_Threshold__c = 0.9,
                NER_Confidence_Threshold__c = 0.9,
                Sentiment_Confidence_Threshold__c = 0.7
            );
            settings.add(testSetting);
        } else {
            settings = [select Id
                ,DeveloperName
                ,Type__c
                ,Additional_Parameters__c
                ,Intent_Confidence_Threshold__c
                ,NER_Confidence_Threshold__c
                ,Sentiment_Confidence_Threshold__c
                ,(select Model_Id__c, Named_Credential_Name__c from External_Nlp_Model_Settings__r)
                from External_Nlp_Service_Setting__mdt
                where DeveloperName = :customMetadataName
                limit 1];
        }
        if (settings.isEmpty()) {
            throw new ExternalNlpServiceException('Invalid setting name', ExternalNlpServiceExceptionCode.INVALID_SETTTING); 
        }
        return settings.get(0);
    }

}